name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # =====================================================
  # QUALITY CHECKS
  # =====================================================
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type checking
        run: npx tsc --noEmit --skipLibCheck

      - name: Linting
        run: npm run lint

      - name: Build check
        run: npm run build
          
      - name: Security audit
        run: npm audit --audit-level=high --omit=dev || echo "Audit found issues but continuing"

  # =====================================================
  # TESTING
  # =====================================================
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success()
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

  # =====================================================
  # DEPLOYMENT
  # =====================================================
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    environment: WACANDA_PROD
    needs: [quality-checks, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

  # =====================================================
  # NOTIFICATION
  # =====================================================
  notify:
    name: Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always() && github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deployment Summary
        run: |
          echo "## 🚀 Deployment Summary"
          echo "**Status:** ${{ needs.deploy.result }}"
          echo "**URL:** https://wacanda.vercel.app"
          echo "**Commit:** ${{ github.sha }}"
          echo "**Time:** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          
          if [ "${{ needs.deploy.result }}" = "success" ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed"
            echo "Check the logs above for details"
          fi
